### ISSUE TITLE
Download link for the current spec file

### ISSUE THREAD

**Issue by neongrau** [Authress-Engineering/openapi-explorer#226]
Saw your comment on the discussion on the rapidDoc repo.

Is there anything like `allow-spec-file-download="true"` that existed in rapiDoc ?
I was hoping for a working option that also honors changing specs via loadSpec from an added dropdown.

**Comment by wparad** [comment]
There is no explicit built in UI component for changing the spec, but there are plenty of available `<slots>` as well as an explicit method to load any spec. To dynamically load a different spec, you can call the:

```js
async loadSpec(spec) - Load a spec from an object or using an remote url.
example: await document.getElementsByTagName('openapi-explorer')[0].loadSpec(specObjectOrUrl);
```

The documentation for that is [here](https://github.com/Authress-Engineering/openapi-explorer/blob/release/2.1/docs/documentation.md#library-api).

Does that solve this problem?
...

For the other issues, I'm struggling to follow how many issues there are here and where explicitly the problems lie. Can you include a minimal reproduction in separate issues for each of the other ones?

**Comment by neongrau** [comment]
> Does that solve this problem? ...

No, the loadSpec actually works exactly like i had it with rapiDoc. At rapiDoc when you set
`<rapidoc llow-spec-file-download="true"...` you would get a button directly below the spec title that allowed downloading the spec file so people can use those in tools like Postman. But the rapiDoc implementation was bugged and always showed the initial `<rapidoc spec-url="initial-spec.yaml"` even after changing it with loadSpec.

> For the other issues, I'm struggling to follow how many issues there are here and where explicitly the problems lie. Can you include a minimal reproduction in separate issues for each of the other ones?

```js
      const docElement = document.querySelector('openapi-explorer');
      const style = document.createElement('style');
      style.innerHTML = `
      .m-btn {
        border-radius: 15px !important;
        box-shadow: none;
      }`;
      docElement.shadowRoot.appendChild(style);
```

Like this (doesn't work).

**Comment by neongrau** [comment]
and also this

```css
    openapi-explorer::part(navbar-operations-header) { /*works*/
      background: linear-gradient(90deg, #0065AD, #02AFC3);
      border-top: none;
      border-bottom: 1px solid rgba(255,255,255, .2);
      font-size: 11px;
    }
    openapi-explorer::part(navbar-components-header) { /* needed but not implemented? */
      background: linear-gradient(90deg, #0065AD, #02AFC3);
      border-top: none;
      border-bottom: 1px solid rgba(255,255,255, .2);
      font-size: 11px;
    }
```
