### ISSUE TITLE
How to style m-btn component

### ISSUE THREAD

**Issue by wparad** [Authress-Engineering/openapi-explorer#227]
@neongrau

```js
const docElement = document.querySelector('openapi-explorer');
      const style = document.createElement('style');
      style.innerHTML = `
      .m-btn {
        border-radius: 15px !important;
        box-shadow: none;
      }`;
      docElement.shadowRoot.appendChild(style);
```

```css
    openapi-explorer::part(navbar-operations-header) { /*works*/
      background: linear-gradient(90deg, #0065AD, #02AFC3);
      border-top: none;
      border-bottom: 1px solid rgba(255,255,255, .2);
      font-size: 11px;
    }
    openapi-explorer::part(navbar-components-header) { /* needed but not implemented? */
      background: linear-gradient(90deg, #0065AD, #02AFC3);
      border-top: none;
      border-bottom: 1px solid rgba(255,255,255, .2);
      font-size: 11px;
    }
```

**Comment by wparad** [comment]
@neongrau can you provide a visual of what the problem is here and how you would like it to look like? This would be the best way to figure out how to either suggest a solution or provide new functionality. Thanks!

**Comment by neongrau** [comment]
currently button look like this:
![Bildschirmfoto 2024-02-06 um 14 27 17](https://github.com/Authress-Engineering/openapi-explorer/assets/179209/a714c2d5-a246-4347-8915-fc59b8f0c803)

but i want to restyle them to look like this:
![Bildschirmfoto 2024-02-06 um 14 30 31](https://github.com/Authress-Engineering/openapi-explorer/assets/179209/3de59483-7d38-434c-913f-57bfb2121c72)

**Comment by neongrau** [comment]
Closed?

**Comment by wparad** [comment]
Okay, now everything is fixed. You would reference the button style changes the same way you might do the other updates. In this case:
```css
openapi-explorer::part(btn--resp) {
      border-radius: 15px !important;
      box-shadow: none;
    }
```

Is probably what you want.
