### ISSUE TITLE
Model schema type shown as "2" instead of "array"

### ISSUE THREAD

**Issue by neongrau** [Authress-Engineering/openapi-explorer#230]
Excerpt of my generic schema defining JsonAPI relationships.
Where the array variant is showing type "2" where "array" should be.

![Bildschirmfoto 2024-02-08 um 13 17 51](https://github.com/Authress-Engineering/openapi-explorer/assets/179209/018581ac-f591-4625-b1ac-c9160971d4d8)

example schema part
```yaml
    relationships:
      type: object
      description: Optional listing of associated records if available
      additionalProperties:
        type: object
        description: key being the name of the relation
        required:
        - data
        properties:
          data:
            anyOf:
            - type: object
              required:
              - id
              - type
              properties:
                id:
                  type: string
                type:
                  type: string
              description: single relation reference in case of one-to-one
            - type: array
              description: array of relation references in case of one-to-many
              items:
                type: object
                required:
                - id
                - type
                properties:
                  id:
                    type: string
                  type:
                    type: string
```
