### ISSUE TITLE
(minor) fixed text about bearer token not always correct

### ISSUE THREAD

**Issue by neongrau** [Authress-Engineering/openapi-explorer#242]
when having 

```yaml
components:
  securitySchemes:
    Bearer:
      description: |
        # Token based authentication Header
        Authenticate and then copy the token into this field without the "Bearer " prefix.
      type: http
      scheme: bearer
```

The leading "Bearer " part is actually optional. So the fixed text saying it needs to be prefixed is a bit misleading.
There are some variants that need it. Though the above example does not.

Not really much of a problem. I just noticed that a previous UI i used required omitting the prefix and openapi-explorer states it's needed, while it's not.

**Comment by wparad** [comment]
What's the context here?

**Comment by wparad** [comment]
The `Bearer` is absolutely required by the OAuth Bearer Token RFC Specification. If your API doesn't require it then that's up to you, but technically not compliant with the OAuth Bearer tokens.

If you don't need the Bearer part, then technically this isn't OAuth, it's just an API key, and of course whatever semantics make sense there for your service should be used.

But as the text there actually matches the specification, it makes sense not to change this, unless the spec changes.

I hope that makes sense.

**Comment by neongrau** [comment]
no not really

```yaml
securityDefinitions:
  APIKey:
    type: apiKey
    name: Authorization
    in: header
```

^ requires you to prefix with `Bearer `

while my example with the UI from
https://swagger.io

having the prefix would result in `Bearer Bearer ....` as the prefix is implied when using `scheme: bearer`
